name: '${projectName}'
version: '${projectVersion}'
main: '${projectMainClass}'
api-version: 1.19
authors: [ CKATEPTb ]
depend: [ Nicotine ]
description: Implements a cloud command inside a DI container that simplifies the description of commands and is similar to Mojang Brigadier.